### ISSUE TITLE
Extract PrePayItem from "StatementBill" adding table

### ISSUE THREAD

**Issue by diegozhu** [alex123bob/FamilyDecoration#35]
Statement bill various in prepay, regular, or qgd types , which means prepay item should not be added into regular bill. We'd better add a button along with 'add bill' button named 'add ppb bill' .

when 'add ppb bill' button is clicked , the modify window show automatically init with one single record/item which named 'prepay item' cause as for ppb type bill , there'll always be one prepay item and only one record for modify, no delete or add feature. Therefore , 'add small item' & 'add blank item' buttons should be hidden.

For further design , qgd type bill show share the same logic with ppb bill which I believe will certainly reduce logical complexity.

**Comment by alex123bob** [comment]
done. @diegozhu
